[package]
name = "map-reduce-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.89"
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
tokio = { version = "1", features = ["time"] }
